%This function breaks complex curvelet coefficients, generated by CtoCcomplex, to real coefficients
%to be used with the inverse curvelet transform.
function C=CcomplextoC(Ccomplex,nbangles)
C=Ccomplex;
for i=1:length(Ccomplex)
    
    
    for j=1:length(Ccomplex{i})/2
        C{i}{j} = real(Ccomplex{i}{j})*sqrt(2);
    end
    
    
    for j=length(Ccomplex{i})/2+1:length(Ccomplex{i})
        C{i}{j} = imag(Ccomplex{i}{j-sum(nbangles(1,i)+nbangles(2,i))})*sqrt(2);
    end
end

end
